// <auto-generated />
using System;
using DesafioTecnico.Softplan.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DesafioTecnico.Softplan.Infra.Migrations
{
    [DbContext(typeof(DesafioTecnicoSoftPlanDbContext))]
    [Migration("20210814184629_Eliton")]
    partial class Eliton
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DesafioTecnico.Softplan.Domain.Classes.Juros", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(2021, 8, 14, 15, 46, 29, 341, DateTimeKind.Local).AddTicks(6817));

                    b.Property<decimal>("Porcentagem")
                        .HasColumnType("numeric(3,2)");

                    b.HasKey("ID");

                    b.ToTable("Juros");
                });
#pragma warning restore 612, 618
        }
    }
}
